### ISSUE TITLE
Problem whit Message from Chat

### ISSUE THREAD

**Issue by Feindfluglp** [jacob1421/Twitch-IRC-API#1]
Hello,
i send a message like this: "test :D hello" and in serial / variables its only "test;".
its a bug, from library

**Comment by jacob1421** [comment]
Could you give me the callback function name you are using and the variable you are accessing?

**Comment by Feindfluglp** [comment]
the function: onPrivMsg and variables message

**Comment by Feindfluglp** [comment]
and the function: onCustomReward its the same problem

**Comment by Feindfluglp** [comment]
my idea its, its the problem whit char.
change the variables whit string?

**Comment by Feindfluglp** [comment]
hello,
you have tested this bug and you can see its a problem?

**Comment by jacob1421** [comment]
@Feindfluglp The issue has been resolved. It was due to how I was setting up the message for parsing. The ":D" was converted to ";D".
