### ISSUE TITLE
Twitch_IRC_API.cpp

### ISSUE THREAD

**Issue by noycebru** [jacob1421/Twitch-IRC-API#4]
in the twitch_IRC_API.cpp file this include "../include/twitch_irc.api.h" should be changed to 
"twitch_irc_api.h"

#include <stdio.h>
#include <string.h>
#include <stdlib.h> 
#include "../include/twitch_irc_api.h"
#include "bot_credentials.h"

Thanks again for this great software!!

**Comment by jacob1421** [comment]
Fixed.
